// src/types/index.ts
// ─────────────────────────────────────────────────────────────────────────────
// Shared TypeScript type definitions for the Novana app.
//
// What is TypeScript?
// TypeScript checks that your data has the right shape.
// For example, if a function expects a number and you pass a string,
// TypeScript shows an error BEFORE you run the code.
// ─────────────────────────────────────────────────────────────────────────────

// ── Cycle status options ──────────────────────────────────────────────────────
export type CycleStatus = 'none' | 'spotting' | 'light' | 'moderate' | 'heavy'

// ── A single day's symptom log ────────────────────────────────────────────────
// Matches the 'symptoms' table in Supabase (Phase 3)
export interface Symptom {
  id?:           string        // UUID, auto-generated by Supabase
  user_id?:      string        // UUID from auth.users
  logged_at?:    string        // ISO date string e.g. "2026-05-13"
  mood:          number        // 1–10
  fatigue:       number        // 1–10
  sleep_hours:   number        // 0–12
  stress:        number        // 1–10
  acne:          number        // 1–10
  cramps:        number        // 1–10
  exercise_mins: number        // 0–120
  cycle_status:  CycleStatus
  notes?:        string
}

// ── User profile ──────────────────────────────────────────────────────────────
export interface Profile {
  id:         string
  email:      string
  full_name?: string
  created_at: string
}

// ── Journal entry ─────────────────────────────────────────────────────────────
export interface JournalEntry {
  id:          string
  user_id:     string
  content:     string
  ai_summary?: string
  created_at:  string
}

// ── AI insight response ───────────────────────────────────────────────────────
export interface InsightResponse {
  summary:      string
  correlations: string[]
  suggestions:  string[]
  disclaimer:   string
}
